id: A85DBA555
title: Aspiration for Future Lives
type: translation
pechas:
- IE873E777
- I11A8DA74
- IEAAF28A1
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:15.672818
  last_modified_at: 2023-01-04 12:49:15.672842
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  IE873E777/B984: CEAB
  I11A8DA74/4E25: CEAB
  IEAAF28A1/F3C7: CEAB
